package lexer

type TokenType string

const (
	TokenEOF     TokenType = "EOF"
	TokenIllegal TokenType = "ILLEGAL"

	TokenIdent     TokenType = "IDENT"
	TokenNumber    TokenType = "NUMBER"
	TokenBigInt    TokenType = "BIGINT"
	TokenString    TokenType = "STRING"
	TokenTemplate  TokenType = "TEMPLATE"
	TokenTrue      TokenType = "TRUE"
	TokenFalse     TokenType = "FALSE"
	TokenNull      TokenType = "NULL"
	TokenUndefined TokenType = "UNDEFINED"

	TokenFunction   TokenType = "FUNCTION"
	TokenClass      TokenType = "CLASS"
	TokenEnum       TokenType = "ENUM"
	TokenExtends    TokenType = "EXTENDS"
	TokenExtern     TokenType = "EXTERN"
	TokenImport     TokenType = "IMPORT"
	TokenExport     TokenType = "EXPORT"
	TokenDefault    TokenType = "DEFAULT"
	TokenNative     TokenType = "NATIVE"
	TokenStatic     TokenType = "STATIC"
	TokenNew        TokenType = "NEW"
	TokenThis       TokenType = "THIS"
	TokenSuper      TokenType = "SUPER"
	TokenVar        TokenType = "VAR"
	TokenLet        TokenType = "LET"
	TokenConst      TokenType = "CONST"
	TokenPrivate    TokenType = "PRIVATE"
	TokenPublic     TokenType = "PUBLIC"
	TokenReturn     TokenType = "RETURN"
	TokenIf         TokenType = "IF"
	TokenElse       TokenType = "ELSE"
	TokenDo         TokenType = "DO"
	TokenWhile      TokenType = "WHILE"
	TokenWith       TokenType = "WITH"
	TokenFor        TokenType = "FOR"
	TokenOf         TokenType = "OF"
	TokenIn         TokenType = "IN"
	TokenSwitch     TokenType = "SWITCH"
	TokenCase       TokenType = "CASE"
	TokenBreak      TokenType = "BREAK"
	TokenContinue   TokenType = "CONTINUE"
	TokenDelete     TokenType = "DELETE"
	TokenDebugger   TokenType = "DEBUGGER"
	TokenTry        TokenType = "TRY"
	TokenCatch      TokenType = "CATCH"
	TokenFinally    TokenType = "FINALLY"
	TokenThrow      TokenType = "THROW"
	TokenAwait      TokenType = "AWAIT"
	TokenAsync      TokenType = "ASYNC"
	TokenYield      TokenType = "YIELD"
	TokenTypeof     TokenType = "TYPEOF"
	TokenVoid       TokenType = "VOID"
	TokenInstanceof TokenType = "INSTANCEOF"
	TokenIs         TokenType = "IS"

	TokenLParen    TokenType = "("
	TokenRParen    TokenType = ")"
	TokenLBrace    TokenType = "{"
	TokenRBrace    TokenType = "}"
	TokenLBracket  TokenType = "["
	TokenRBracket  TokenType = "]"
	TokenSemicolon TokenType = ";"
	TokenComma     TokenType = ","
	TokenColon     TokenType = ":"
	TokenDot       TokenType = "."
	TokenEllipsis  TokenType = "..."
	TokenQuestion  TokenType = "?"
	TokenHash      TokenType = "#"
	TokenAt        TokenType = "@"

	TokenAssign        TokenType = "="
	TokenAddAssign     TokenType = "+="
	TokenSubAssign     TokenType = "-="
	TokenMulAssign     TokenType = "*="
	TokenPowAssign     TokenType = "**="
	TokenDivAssign     TokenType = "/="
	TokenModAssign     TokenType = "%="
	TokenBitAndAssign  TokenType = "&="
	TokenBitOrAssign   TokenType = "|="
	TokenBitXorAssign  TokenType = "^="
	TokenShlAssign     TokenType = "<<="
	TokenShrAssign     TokenType = ">>="
	TokenUShrAssign    TokenType = ">>>="
	TokenAndAssign     TokenType = "&&="
	TokenOrAssign      TokenType = "||="
	TokenNullishAssign TokenType = "??="
	TokenArrow         TokenType = "=>"

	TokenPlus          TokenType = "+"
	TokenMinus         TokenType = "-"
	TokenIncrement     TokenType = "++"
	TokenDecrement     TokenType = "--"
	TokenStar          TokenType = "*"
	TokenPower         TokenType = "**"
	TokenSlash         TokenType = "/"
	TokenPercent       TokenType = "%"
	TokenBang          TokenType = "!"
	TokenEq            TokenType = "=="
	TokenStrictEq      TokenType = "==="
	TokenNe            TokenType = "!="
	TokenStrictNe      TokenType = "!=="
	TokenLt            TokenType = "<"
	TokenLte           TokenType = "<="
	TokenGt            TokenType = ">"
	TokenGte           TokenType = ">="
	TokenAnd           TokenType = "&&"
	TokenOr            TokenType = "||"
	TokenNullish       TokenType = "??"
	TokenQuestionDot   TokenType = "?."
	TokenBitAnd        TokenType = "&"
	TokenBitOr         TokenType = "|"
	TokenBitXor        TokenType = "^"
	TokenBitNot        TokenType = "~"
	TokenShiftLeft     TokenType = "<<"
	TokenShiftRight    TokenType = ">>"
	TokenUnsignedShift TokenType = ">>>"
)

type Token struct {
	Type    TokenType
	Literal string
	Line    int
	Column  int
}
