package lexer

type TokenType string

const (
	TokenEOF           TokenType = "EOF"
	TokenIllegal       TokenType = "ILLEGAL"
	TokenFunction      TokenType = "FUNCTION"
	TokenClass         TokenType = "CLASS"
	TokenExtends       TokenType = "EXTENDS"
	TokenExtern        TokenType = "EXTERN"
	TokenImport        TokenType = "IMPORT"
	TokenNative        TokenType = "NATIVE"
	TokenStatic        TokenType = "STATIC"
	TokenNew           TokenType = "NEW"
	TokenTypeof        TokenType = "TYPEOF"
	TokenInstanceof    TokenType = "INSTANCEOF"
	TokenThis          TokenType = "THIS"
	TokenSuper         TokenType = "SUPER"
	TokenVar           TokenType = "VAR"
	TokenLet           TokenType = "LET"
	TokenConst         TokenType = "CONST"
	TokenPrivate       TokenType = "PRIVATE"
	TokenPublic        TokenType = "PUBLIC"
	TokenReturn        TokenType = "RETURN"
	TokenIf            TokenType = "IF"
	TokenElse          TokenType = "ELSE"
	TokenWhile         TokenType = "WHILE"
	TokenFor           TokenType = "FOR"
	TokenOf            TokenType = "OF"
	TokenIn            TokenType = "IN"
	TokenSwitch        TokenType = "SWITCH"
	TokenCase          TokenType = "CASE"
	TokenDefault       TokenType = "DEFAULT"
	TokenBreak         TokenType = "BREAK"
	TokenContinue      TokenType = "CONTINUE"
	TokenDelete        TokenType = "DELETE"
	TokenTry           TokenType = "TRY"
	TokenCatch         TokenType = "CATCH"
	TokenFinally       TokenType = "FINALLY"
	TokenThrow         TokenType = "THROW"
	TokenTrue          TokenType = "TRUE"
	TokenFalse         TokenType = "FALSE"
	TokenNull          TokenType = "NULL"
	TokenUndefined     TokenType = "UNDEFINED"
	TokenIdent         TokenType = "IDENT"
	TokenNumber        TokenType = "NUMBER"
	TokenString        TokenType = "STRING"
	TokenTemplate      TokenType = "TEMPLATE"
	TokenLParen        TokenType = "("
	TokenRParen        TokenType = ")"
	TokenLBrace        TokenType = "{"
	TokenRBrace        TokenType = "}"
	TokenLBracket      TokenType = "["
	TokenRBracket      TokenType = "]"
	TokenSemicolon     TokenType = ";"
	TokenAssign        TokenType = "="
	TokenAddAssign     TokenType = "+="
	TokenSubAssign     TokenType = "-="
	TokenMulAssign     TokenType = "*="
	TokenDivAssign     TokenType = "/="
	TokenArrow         TokenType = "=>"
	TokenEq            TokenType = "=="
	TokenStrictEq      TokenType = "==="
	TokenNe            TokenType = "!="
	TokenStrictNe      TokenType = "!=="
	TokenBang          TokenType = "!"
	TokenQuestion      TokenType = "?"
	TokenQuestionDot   TokenType = "?."
	TokenNullish       TokenType = "??"
	TokenNullishAssign TokenType = "??="
	TokenLt            TokenType = "<"
	TokenLte           TokenType = "<="
	TokenGt            TokenType = ">"
	TokenGte           TokenType = ">="
	TokenComma         TokenType = ","
	TokenColon         TokenType = ":"
	TokenDot           TokenType = "."
	TokenEllipsis      TokenType = "..."
	TokenHash          TokenType = "#"
	TokenPlus          TokenType = "+"
	TokenMinus         TokenType = "-"
	TokenStar          TokenType = "*"
	TokenSlash         TokenType = "/"
	TokenAnd           TokenType = "&&"
	TokenOr            TokenType = "||"
	TokenAndAssign     TokenType = "&&="
	TokenOrAssign      TokenType = "||="
)

type Token struct {
	Type    TokenType
	Literal string
	Line    int
	Column  int
}
